#!/usr/bin/python3
import sys
from glob import glob
from os import path
import signal
from time import sleep

#dummy capture signal
def _signal(signum, frame):
    pass

#########################################################
# Main                                                  # 
#########################################################  
sys.path.insert(0, '/opt/Domotion/apps')

appfiles = glob("/opt/Domotion/apps/app_*.py")

signal.signal(signal.SIGINT, _signal)
signal.signal(signal.SIGTERM, _signal)

apps = []
for appfile in appfiles:
    appname=path.splitext(path.basename(appfile))[0]
    app = getattr(__import__(appname), "app")
    apps.append(app())

signal.pause()

for app in apps:
    app.terminate()

